---
- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true
  become_user: root
  become_method: su
  gather_facts: false

  pre_tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest
        update_cache: true

  roles:
    - name: common/debug
    - name: common/java
    - name: common/kernel
    - name: common/locale
    - name: common/network
    - name: common/packages
    - name: middleware/apache
    - name: middleware/docker
    # - name: middleware/kafka
    - name: middleware/nginx

  post_tasks:
    - name: post_tasks
      shell: "post_tasks"
