
- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true
  become_user: root
  become_method: su
  gather_facts: true

  tasks:
    - name: Fix modperl config
      lineinfile:
        dest=/tmp/test.txt
        insertafter=EOF
        line={{ item }}
      with_items:
        - '1行目'
        - '2行目'

    - name: clone news
      git:
        clone: true
        dest: /tmp/perlv
        recursive: true
        repo: gitlab_company:ryuichi1208/plever.git
        version: HEAD
