---
- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true
  become_user: root
  become_method: su
  gather_facts: false

  pre_tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest
        update_cache: true

  roles:
    - name: common/kernel
    - name: common/locale
    - name: common/packages
      tags: common/packages
    - name: common/network
    - name: middleware/docker
