---
- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true
  become_user: root
  become_method: su
  gather_facts: true
  connection: local
  tasks:
    - name: Ping
      ping:

  pre_tasks:
    - name: Pring Server Info
      debug: var=ansible_facts

  roles:
    - name: linux/common/packages
