---

- name: Include Kernel Prameter vars
  include_vars: linux.yml

- name: Setting Kernel Parameter
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes
  with_items:
    - "{{ kernel_parameter }}"
