---

- name: ./configure
  shell: >
    cd {{ vim_make_dir }} &&
    ./configure \
    --enable-fail-if-missing \
    --with-features=huge \
    --disable-selinux \
    --enable-luainterp \
    --enable-perlinterp \
    --enable-pythoninterp=dynamic \
    --with-python-config-dir=/usr/lib64/python2.7/config \
    --enable-python3interp=dynamic \
    --with-python3-config-dir=/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu \
    --enable-rubyinterp=dynamic \
    --with-ruby-command=/usr/bin/ruby \
    --enable-cscope \
    --enable-fontset \
    --enable-multibyte \
    vi_cv_path_python3=/usr/bin/python3.6

- name: make all
  make:
    chdir: "{{ vim_make_dir }}"
    target: all

- name: make install
  make:
    chdir: "{{ vim_make_dir }}"
    target: install
