---

- name: Install epel repo
  yum:
    name: "epel-release.noarch"
    state: latest

- name: Install basic packages
  yum:
    name: "{{ install_packages }}"
    update_cache: "{{ update_cache_enabled }}"
    state: present
    lock_timeout: 30
    validate_certs: true
